# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 229cb559aa253c03ad26f2fd20962262ae54f8e3815837dedce5c143a1891d98f1a90ea80933c69bf8705674152b549036494e4d4882986aa3033f7416c614b9

test:
  secret_key_base: 063805c23d7494db77ad6cdf5415f1796202c21931f60bc27b620dc0b02782f816b5d3302a58209066511e9433b3b8e0227cf96e3b14becb828895ca3871b3bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
